spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/BankDB
    username: postgres
    password: ""
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update